nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

logFilters:
  - code: YN0002 # Ignore "package-lock.json found" warning
    level: discard
  - code: YN0060 # Ignore "non-optimal resolution" warning
    level: discard

packageExtensions:
  "cloudinary@*":
    dependencies:
      "q": "^2.0.3" 